shape_msgs/Mesh mesh

string frame_id

# With the given start pose, the algorithm will use the closest sub-facet centre as the start of the coverage path
geometry_msgs/PoseStamped start_pose

---
nav_msgs/Path coverage